version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: org.jetbrains.kotlin:kotlin-allopen
    versions:
    - 1.4.32
  - dependency-name: org.jetbrains.kotlin:kotlin-gradle-plugin
    versions:
    - 1.4.32
  - dependency-name: org.junit.jupiter:junit-jupiter-engine
    versions:
    - 5.7.1
